version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: >-
    $ErrorActionPreference = "Stop";

    ./versionize.ps1 $env:APPVEYOR_BUILD_NUMBER | %{ Update-AppveyorBuild -Version $_ };

    $env:REPO_TAG_DESCRIPTION = (git tag -l --format='%(contents)' $env:APPVEYOR_REPO_TAG_NAME | Where-Object {$_}) -join "<br />";

    Write-Host $env:REPO_TAG_DESCRIPTION;
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack ShinySwitch\ShinySwitch.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*/**/*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: rTAOxhsBekNlEb9IN6Iyy5mayYbiTTIWidYKB4f1ZyRbwiIeqjFr0x6qDZQM6RYP